### ISSUE TITLE
Createinvoice.php doesn't work with any other email ID registered with Paypal as verified Business

### ISSUE THREAD

**Issue by referjs** [paypal/invoice-sdk-php#12]
Hi,

https://github.com/paypal/invoice-sdk-php/blob/master/samples/createInvoice.php
This script only works with sample email, and not with any of our verified paypal emails.
Can someone help with this please?

Thanks

**Comment by hebrew878** [comment]
may be you need to use live api endpoint for live accounts.

**Comment by juwlee** [comment]
@referjs As @hebrew878 pointed out, the sample code points to sandbox with sandbox account. Please try live account when hitting live system.
