### ISSUE TITLE
I have find a Reflected XSS vulnerability in this sdk

### ISSUE THREAD

**Issue by jgj212** [paypal/invoice-sdk-php#13]
Hello:
I have find a Reflected XSS vulnerability in this sdk.

The vulnerability exists due to insufficient filtration of user-supplied data in “permToken” HTTP GET parameter that will be passed to “invoice-sdk-php-master/samples/permissions.php”. The infected source code is line 9, there is no protection on $_GET['permToken']; if $_GET['permToken'] contains evil js code, line 9 will trigger untrusted code to be excuted on the browser side.
![image](https://cloud.githubusercontent.com/assets/1484292/23160498/b4a2d856-f861-11e6-9a9e-4a79c3259180.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/invoice-sdk-php-master/samples/permissions.php?permToken="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![image](https://cloud.githubusercontent.com/assets/1484292/23160577/fe788782-f861-11e6-8ab2-b4e888a727d9.png)

Discoverer: Haojun Hou, DongWang in ADLab of Venustech
Email: jgj212@gmail.com

**Comment by pp-randy** [comment]
Adding internal tracking: BTDXCLTS-283
