### ISSUE TITLE
Customization of invoices

### ISSUE THREAD

**Issue by shinijaQB** [paypal/invoice-sdk-php#17]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by shinijaQB** [comment]
Hi,

How can I remove the label 'shipping' from invoices created using invoice SDK in PHP?

**Comment by shinijaQB** [comment]
Getinvoicedetails API not giving response for a cancelled invoice. Help me

**Comment by pp-randy** [comment]
Have you already reviewed our newer SDK for invoicing? 
https://github.com/paypal/PayPal-PHP-SDK

**Comment by shinijaQB** [comment]
Yes. But I had used this invoice SDK in my application. Now Getinvoicedetails API not giving response for a cancelled invoice.

**Comment by pp-randy** [comment]
Can you send a screenshot of what you are seeing to provide additional clarity?

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please submit a new issue under https://github.com/paypal/PayPal-PHP-SDK if you have questions with the new REST invoice SDK.
